CREATE TABLE raciones (
  Id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) NOT NULL DEFAULT '',
  descripcion varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (Id)
) AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;